include:
  - project: 'dracoon/cicd/pipeline/web-guild-ci'
    ref: "4.0.5"
    file:
      - "base.yml"
      # prepare
      - "prepare.yml"
      # build
      - "build-service.yml"
      # test
      - "test-service.yml"
      - "lint-service.yml"
      - "dependency-scanning-service.yml"
      - "secret-detection-service.yml"
      - "sonar-service.yml"

# --- GLOBAL SETTINGS / VARIABLES ---------------------------------------------

variables:
  NAME: dracoon-sdk-crypto-javascript
  # https://gitlab.com/gitlab-org/gitlab/-/issues/525496
  DS_MAJOR_VERSION: 5.8.7

  NODE_VERSION: 20.11.1

  ENABLE_ARTIFACT_PUBLISHING: 'true'
  ENABLE_PUBLIC_ARTIFACT_PUBLISHING: 'true'
  ENABLE_INTEGRATION_TESTING: 'true'

  SECRET_DETECTION_EXCLUDED_PATHS: "test"

build-service:
  artifacts:
    paths:
      - lib/