include:
  - project: 'dracoon/cicd/pipeline/web-guild-ci'
    file: 'pipeline-commons.yml'
    ref: '3.0.3'

# --- GLOBAL SETTINGS / VARIABLES ---------------------------------------------

variables:
  NAME: dracoon-sdk-crypto-javascript
  JIRA_PROJECT_ID: SDKCRYPTJS

  NODE_VERSION: 20.11.1

  ENABLE_ARTIFACT_PUBLISHING: 'true'
  ENABLE_PUBLIC_ARTIFACT_PUBLISHING: 'true'
  ENABLE_CONTAINER_IMAGES: 'false'
  ENABLE_CONTAINER_SCANNING: 'false'

# Global defaults, set on every job that doesn't override
default:
  id_tokens:
    ID_TOKEN:
      aud: https://vault.dracoon.net

integration-test-service:
  stage: test
  script:
    - npm run integration-test:ci

build-service:
  artifacts:
    paths:
      - lib/

.dev-workflow:
  job-rules:
    publish-service:
      # release branch should be automatic
      - if: $PIPELINE_TRIGGER == "branch" &&
            $PIPELINE_CONTEXT =~ /^(release|snapshot)$/
        when: always
      # other branch should be optional manual
      - when: manual
        allow_failure: true
