include:
  - project: 'dracoon/cicd/pipeline/web-guild-ci'
    ref: "4.2.0"
    file:
      - build-service.yml
      - test-service.yml
      - lint-service.yml
      - sonar-service.yml

# --- GLOBAL SETTINGS / VARIABLES ---------------------------------------------

variables:
  NAME: dracoon-sdk-crypto-javascript
  NODE_VERSION: 24.14.1

  ENABLE_ARTIFACT_PUBLISH: 'true'
  ENABLE_PUBLIC_ARTIFACT_PUBLISH: 'true'
  ENABLE_INTEGRATION_TESTING: 'true'

  SECRET_DETECTION_EXCLUDED_PATHS: "test"

build:
  artifacts:
    paths:
      - lib/