include:
  - project: 'dracoon/cicd/pipeline/pipeline-commons'
    file: 'pipeline-commons.yml'
    ref: '2.0.0'

# --- GLOBAL SETTINGS / VARIABLES ---------------------------------------------

variables:
  NAME: dracoon-sdk-crypto-javascript
  JIRA_PROJECT_ID: SDKCRYPTJS
  
  ENABLE_INTEGRATION_TESTING: 'false'
  ENABLE_ARTIFACT_PUBLISHING: 'true'
  ENABLE_PUBLIC_ARTIFACT_PUBLISHING: 'true'
  ENABLE_CONTAINER_IMAGES: 'false'
