include:
  - project: 'dracoon/cicd/pipeline/pipeline-commons'
    file: 'pipeline-commons.yml'
    ref: '2.5.4'

# --- GLOBAL SETTINGS / VARIABLES ---------------------------------------------

variables:
  NAME: dracoon-sdk-crypto-javascript
  JIRA_PROJECT_ID: SDKCRYPTJS

  NODE_VERSION: 20.11.1

  ENABLE_ARTIFACT_PUBLISHING: 'true'
  ENABLE_PUBLIC_ARTIFACT_PUBLISHING: 'true'
  ENABLE_CONTAINER_IMAGES: 'false'

# Global defaults, set on every job that doesn't override
default:
  id_tokens:
    ID_TOKEN:
      aud: https://vault.dracoon.net

integration-test-service:
  stage: test
  script:
    - npm run integration-test:ci

build-service:
  artifacts:
    paths:
      - lib/

.dev-workflow:
  job-rules:
    publish-service:
      # hotfix branch should be manual
      - if: $PIPELINE_TRIGGER == "branch" && 
            $PIPELINE_CONTEXT == "release" && 
            $CI_COMMIT_BRANCH =~ /^release\/\d+\.\d+\.[^0]\d*$/
        when: manual
      # release branch should be automatic
      - if: $PIPELINE_TRIGGER == "branch" &&
            $PIPELINE_CONTEXT =~ /^(release|snapshot)$/
      # other branch should be optional manual
      - if: ($PIPELINE_TRIGGER == "mr" &&
            $PIPELINE_CONTEXT != "renovate") ||
            $PIPELINE_CONTEXT == "default"
        when: manual
        allow_failure: true
